// <auto-generated />
using System;
using CloudExchange.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudExchange.Persistence.Migrations
{
    [DbContext(typeof(DescriptorContext))]
    partial class DescriptorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudExchange.Domain.Aggregates.DescriptorAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Lifetime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Upload")
                        .HasColumnType("text");

                    b.Property<long>("Weight")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("CloudExchange.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("LockedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("LockedUntil")
                        .HasColumnType("bigint");

                    b.Property<int>("Locktime")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("CloudExchange.Domain.Aggregates.DescriptorAggregate", b =>
                {
                    b.OwnsOne("CloudExchange.Domain.ValueObjects.DescriptorCredentialsValueObject", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("DescriptorAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DownloadHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DownloadHash");

                            b1.Property<string>("RootHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RootHash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Salt");

                            b1.HasKey("DescriptorAggregateId");

                            b1.ToTable("Descriptors");

                            b1.WithOwner()
                                .HasForeignKey("DescriptorAggregateId");
                        });

                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
