version: "3.9"

services:
  descriptor_db:
    container_name: descriptor_db
    image: mysql:latest
    restart: always
    environment:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: changeme
        MYSQL_ROOT_PASSWORD: qwerty
    volumes:
        - ./CloudExchange.Data/DescriptorDb:/var/lib/mysql
    ports:
        - 3306:3306
    networks:
        - application
        
  hangfire_db:
    container_name: hangfire_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./CloudExchange.Data/HangfireDb:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"
    networks:
      - application
      
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 5000:8080
    networks:
        - application
        
  cloudexchange_service:
    container_name: cloudexchange_service
    restart: always
    build: 
      context: .
      dockerfile: .\CloudExchange.API\Dockerfile
    ports:
      - 7000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./CloudExchange.Data/Files:/app/files
    depends_on:
      - descriptor_db
      - hangfire_db
    networks:
      - application
    
networks:
  application:
    driver: bridge